const images = [
  {
    src: "/public/images/back-lit-cat.jpg",
    title: "Backlit Cat",
    description: "A painting of my room mate",
    date: "",
    tags: ["ipad", "procreate"],
    featured: true,
  },
  {
    src: "/public/images/beach-bush.jpg",
    title: "Beach Bush",
    description:
      "Took a picture at the beach on one of my bike rides and felt the need to paint it",
    date: "",
    tags: ["ipad", "procreate"],
    featured: true,
  },
  {
    src: "/public/images/burger.jpg",
    title: "Impossible Whopper",
    description: "My attempt at painting something with hyper-realistic",
    date: "",
    tags: ["ipad", "procreate"],
    featured: true,
  },
  {
    src: "/public/images/cat-in-box.JPG",
    title: "Cat in Box",
    description: "a painting of a friends cat I did for her birthday present",
    date: "",
    tags: ["ipad", "procreate"],
    featured: true,
  },
  {
    src: "/public/images/coffee-grinder-01.jpg",
    title: "Mazzer Coffee Grinder",
    description: "my first try at painting without outlines",
    date: "",
    tags: ["ipad", "procreate"],
    featured: true,
  },
  {
    src: "/public/images/coffee-grinder-02.jpg",
    title: "Another Mazzer Coffee Grinder",
    description: "I basically paint these guys when I'm bored at a coffee shop",
    date: "",
    tags: ["ipad", "procreate"],
    featured: true,
  },
  {
    src: "/public/images/crying-trio.PNG",
    title: "The Crying Trio",
    description: "a doodle in my journal when I was feeling overwhelmed",
    date: "",
    tags: ["ipad", "procreate"],
    featured: true,
  },
  {
    src: "/public/images/cup-in-shoe.PNG",
    title: "Cup in Shoe",
    description: "My Mona Lisa. My love letter to San Francisco",
    date: "",
    tags: ["ipad", "procreate"],
    featured: true,
  },
  {
    src: "/public/images/cup.JPG",
    title: "Cup",
    description: "When I started to really get into Procreate",
    date: "",
    tags: ["ipad", "procreate"],
    featured: true,
  },
  {
    src: "/public/images/daniel-cowboy.PNG",
    title: "Daniel",
    description: "A quick study of Daniel on the set of There Will be Blood",
    date: "",
    tags: ["ipad", "procreate"],
    featured: true,
  },
  {
    src: "/public/images/eating-graham-cracker.jpg",
    title: "Chomp Chomp",
    description: "",
    date: "",
    tags: ["ipad", "procreate"],
    featured: true,
  },
  {
    src: "/public/images/floating-in-space.PNG",
    title: "Floater",
    description: "",
    date: "",
    tags: ["ipad", "procreate"],
    featured: true,
  },
  {
    src: "/public/images/fox-running-sprite.gif",
    title: "Fox running sprite sheet",
    description: "",
    date: "",
    tags: ["ipad", "procreate"],
    featured: true,
  },
  {
    src: "/public/images/graveller.PNG",
    title: "Graveler",
    description:
      "Started playing my old pokemon games again, and wanted a pastel painting of my team",
    date: "",
    tags: ["ipad", "procreate"],
    featured: true,
  },
  {
    src: "/public/images/halloween-over.PNG",
    title: "Summer's over",
    description: "",
    date: "",
    tags: ["ipad", "procreate"],
    featured: true,
  },
  {
    src: "/public/images/kinto-mug-01.JPG",
    title: "Kinto mug on couch",
    description: "My first Procreate Painting using the Blocking technique",
    date: "",
    tags: ["ipad", "procreate"],
    featured: true,
  },
  {
    src: "/public/images/knight-helmet-ship.jpg",
    title: "Pew Pew",
    description: "concept for one of my video games (secret)",
    date: "",
    tags: ["ipad", "procreate"],
    featured: true,
  },
  {
    src: "/public/images/lake-merrit.PNG",
    title: "Finger Painting at Lake Merrit",
    description: "",
    date: "",
    tags: ["ipad", "procreate"],
    featured: true,
  },
  {
    src: "/public/images/lemon-tree.PNG",
    title: "Orange Tree in Los Feliz",
    description: "",
    date: "",
    tags: ["ipad", "procreate"],
    featured: true,
  },
  {
    src: "/public/images/lemons-while-stressed.PNG",
    title: "Painting Lemons While Stressed",
    description: "",
    date: "",
    tags: ["ipad", "procreate"],
    featured: true,
  },
  {
    src: "/public/images/mountain.JPG",
    title: "Mountain",
    description: "",
    date: "",
    tags: ["ipad", "procreate"],
    featured: true,
  },
  {
    src: "/public/images/orange-yoshi.PNG",
    title: "Yoshi",
    description: "",
    date: "",
    tags: ["ipad", "procreate"],
    featured: true,
  },
  {
    src: "/public/images/recycling-truck.PNG",
    title: "Recycling",
    description: "",
    date: "",
    tags: ["ipad", "procreate"],
    featured: true,
  },
  {
    src: "/public/images/startled-cat.JPG",
    title: "Startled Cat",
    description: "",
    date: "",
    tags: ["ipad", "procreate"],
    featured: true,
  },
  {
    src: "/public/images/suit.jpg",
    title: "Suit up",
    description: "Concept for my space game",
    date: "",
    tags: ["ipad", "procreate"],
    featured: true,
  },
  {
    src: "/public/images/talking-to-family.PNG",
    title: "Phone Calls with Family",
    description: "",
    date: "",
    tags: ["ipad", "procreate"],
    featured: true,
  },
  {
    src: "/public/images/tape-on-string.PNG",
    title: "Tape on String",
    description: "",
    date: "",
    tags: ["ipad", "procreate"],
    featured: true,
  },
  {
    src: "/public/images/view-from-dolores.PNG",
    title: "Views From Dolores",
    description: "",
    date: "",
    tags: ["ipad", "procreate"],
    featured: true,
  },
  {
    src: "/public/images/yellow-cup.PNG",
    title: "Yellow Cup",
    description: "",
    date: "",
    tags: ["ipad", "procreate"],
    featured: true,
  },
];

export { images };
